# Generated by Django 3.2.15 on 2022-08-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='item_five',
            new_name='five',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='item_four',
            new_name='four',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='item_one',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='item_three',
            new_name='three',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='item_two',
            new_name='two',
        ),
    ]
