# Generated by Django 3.2.15 on 2022-08-10 23:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('journal', '0002_auto_20220810_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
