# Generated by Django 3.2.15 on 2022-08-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_on']},
        ),
    ]
